### ISSUE TITLE
Connection to node doesn't work in 0.4.9

### ISSUE THREAD

**Issue by L3odr0id** [polkawallet-io/sdk#32]
**Describe the bug**
In example connection to node fails on android, because `webViewController` is never initialized in `_web` in `SubstrateService`. Interesting fact that it works fine on iOS.

**To Reproduce**
1. Launch ./example
2. Tap 'connect' button

**Expected behavior**
I expect to get an initialized webview after calling `plugin.sdk.init()`

**Smartphone:**
 - Device: Mi 9T
 - OS: Android
 - Version 0.4.9

**Additional context**
Error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
  #0      WebViewRunner.evalJavascript package:polkawallet_sdk/service/webViewRunner.dart:199
  #1      WebViewRunner.connectNode package:polkawallet_sdk/service/webViewRunner.dart:221
  #2      PolkawalletApi.connectNode package:polkawallet_sdk/api/api.dart:93
  #3      _MyHomePageState._connectNode package:polkawallet_sdk_example/main.dart:115
  #4      _MyHomePageState.build.<anonymous closure> package:polkawallet_sdk_example/main.dart:159
  #5      _InkResponseState._handleTap package:flutter/…/material/ink_well.dart:1005
```

**Comment by L3odr0id** [comment]
Works fine in 0.5.1
